### ISSUE TITLE
Code kingdom app

### ISSUE THREAD

**Issue by masters3d** [davidary/davidarysandbox#1]
Do you have a repo go the app your thinking about for this weekend?

**Comment by davidary** [comment]
Not yet. We will write start writing the code at the event. Are you interested in participating / join the team? 
Let me know if you have any questions.

**Comment by masters3d** [comment]
Yes. I know some Python and iOS using Swiftlang. Are you thinking web app? Mobile? What do you have in mind for the back end?

**Comment by davidary** [comment]
Great! Thank you for your interest.

We are currently planning to have the front end as a mobile web app (HTML, CSS, jquery) and use PhoneGap to deploy it on the phone (Android, iOS). Back end would be in Microsoft .NET stack (C#, ASP .NET, SQL Server). Those are the technology stack that our team is currently have expertise on. 

Do you know any of these technology stack?

Or we could also do, in addition, to have the front end in native iOS that talks to the .NET Web Service back end - since you know iOS.

What do you think?

**Comment by masters3d** [comment]
Nice! I don't know those stacks right now. If I can find anothe iOS person
and if it makes sense for your app I think that would work. Thanks for all
the info. I'll see you Friday.
